# Generated by Django 5.1 on 2024-08-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='business',
            name='revenue_per_annum',
        ),
        migrations.RemoveField(
            model_name='business',
            name='total_employees',
        ),
    ]
