# Generated by Django 5.1 on 2024-08-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0002_remove_business_location_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='user',
        ),
    ]
