# Generated by Django 5.1 on 2024-08-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referal', '0003_remove_modules_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='services',
            name='modules_interested_in',
        ),
        migrations.AddField(
            model_name='services',
            name='modules_interested_in',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
